---

antora:
  name: modules
  dir: www
  modules:
    - name: index
      label: Manipulating File Contents
    - name: module-02
      label: Viewing the end of log files with 'tail'
    - name: module-03
      label: Locating Files
    - name: module-04
      label: Searching for text within files and outputs
    - name: module-05
      label: Using 'df' to check disk usage
    - name: module-06
      label: Viewing processes
    - name: module-07
      label: Using 'free' to view information about the system memory usage

tabs:
  - name: ">_ root"
    port: 443
    path: /tty1
    user: root
    host: rhel
  - name: ">_ rhel"
    port: 443
    path: /tty2
    user: rhel
    host: rhel