=== Using 'free' to view information about the system memory usage

Processes require memory to run, so when the system is running low on
free memory it can slow down significantly. The `+free+` command is
useful for quickly getting a summary of memory usage.

[source,bash,role=execute]
----
free -h
----

The `+-h+` option outputs the information in a human-readable format.

[source,bash]
----
      total  used   free   shared  buff/cache  available
Mem:  3.5Gi  954Mi  889Mi  11Mi    2.0Gi       2.6Gi
Swap: 0B     0B     0B
----

Let’s launch `+top+` again but this time we’ll run it in the background
by adding a `+&+`.

[source,bash,role=execute]
----
top &
----

[source,bash]
----
top &
[1] 31588
----

If the available memory is very low, the fourth column of `+ps au+` can
be used for finding which processes are the culprits. To sort the output
by memory usage, add the `+--sort=-%mem+` option:

[source,bash,role=execute]
----
ps au --sort=-%mem
----

[source,bash]
----
ps -au --sort=-%mem
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root       31589  0.0  0.1  18224  6352 pts/0    R+   11:59   0:00 ps au --sort=-%mem
root       30139  0.0  0.1   8384  5136 pts/0    Ss   11:17   0:00 -bash
rhel       30143  0.0  0.1   8252  4972 pts/1    Ss+  11:17   0:00 -bash
root       31588  0.0  0.0   9984  3560 pts/0    T    11:59   0:00 top
root        1022  0.0  0.0   5612  1092 ttyS0    Ss+  11:08   0:00 /sbin/agetty -o -p -- \u --keep-baud 115200,57600,38400,9600 - vt220
root        1021  0.0  0.0   3044  1088 tty1     Ss+  11:08   0:00 /sbin/agetty -o -p -- \u --noclear - linux
----

Suppose you no longer needed `+top+` and wanted to free up the resources
being used by this process. One option would be to return to terminal
that it is running in and quit it. However, it is simpler in most cases
to use the `+kill+` command. The process ID shown in the `+ps+` output
is how you refer to the process when killing it. Kill the `+top+`
process from this terminal:

[source,bash,role=execute]
----
kill -9 $(pidof top)
----

Here’s what you should see in the terminal.

[source,bash]
----
root@bastion:~# ps -au
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         820  0.0  0.0  13656  1716 tty1     Ss+  18:33   0:00 /sbin/agetty -o -p -- \u --nocl
root         821  0.0  0.0  16224  2060 ttyS0    Ss+  18:33   0:00 /sbin/agetty -o -p -- \u --keep
root        2533  0.0  0.1  26112  3760 pts/0    Ss   18:48   0:00 /bin/bash
root        2696  0.0  0.1  51632  3812 pts/0    T    18:52   0:00 top
root        2698  0.0  0.1  58728  3944 pts/0    R+   18:53   0:00 ps -au
root@bastion:~# kill -9 2696
root@bastion:~# ps -au
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         820  0.0  0.0  13656  1716 tty1     Ss+  18:33   0:00 /sbin/agetty -o -p -- \u --nocl
root         821  0.0  0.0  16224  2060 ttyS0    Ss+  18:33   0:00 /sbin/agetty -o -p -- \u --keep
root        2533  0.0  0.1  26112  3760 pts/0    Ss   18:48   0:00 /bin/bash
root        2699  0.0  0.1  58728  3920 pts/0    R+   18:53   0:00 ps -au
[1]+  Killed                  top
----

This does not show any output, but you can see that `+top+` is no longer
running.

If you want more exercises on this topic, more information on process
management can be found in the
https://lab.redhat.com/service-admin[Service Admin Basics lab].
